In [1]:
import numpy as np
import pandas as pd
import sys
from pandas import Series, DataFrame


In [30]:
# Series
obj = Series([4, 7, -8, -2])
print(obj)
print(obj.values, obj.index)

0    4
1    7
2   -8
3   -2
dtype: int64
[ 4  7 -8 -2] RangeIndex(start=0, stop=4, step=1)


In [31]:
obj2 = Series([4, 7, -8, -2], index=["a", "b", "c", "d"])
print(obj2)
print(obj2.index)

a    4
b    7
c   -8
d   -2
dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='object')


In [32]:
print(obj2["a"])

4


In [33]:
obj2[obj2>0]

a    4
b    7
dtype: int64

In [34]:
obj2*2

a     8
b    14
c   -16
d    -4
dtype: int64

In [35]:
np.exp(obj2)

a      54.598150
b    1096.633158
c       0.000335
d       0.135335
dtype: float64

In [36]:
"a" in obj2

True

In [37]:
"a" in obj

False

In [38]:
dict_data = {"Ohio" : 35000, "Texas": 40000, "Oregon": 16000, "Utah": 5000}
obj3 = Series(dict_data)
print(obj3)

Ohio      35000
Oregon    16000
Texas     40000
Utah       5000
dtype: int64


In [39]:
states = ["California", "Ohio", "Texas", "Oregon"]
obj4 = Series(dict_data, index=states)   # index数组里面没有的键值对被自动忽略, index里面有/字典里面没有的自动设置值为Nan
print(obj4)

California        NaN
Ohio          35000.0
Texas         40000.0
Oregon        16000.0
dtype: float64


In [40]:
print(pd.isnull(obj4)) # 判断缺失值
print(pd.notnull(obj4))
print(obj4.isnull())
print(obj4.notnull())

California     True
Ohio          False
Texas         False
Oregon        False
dtype: bool
California    False
Ohio           True
Texas          True
Oregon         True
dtype: bool
California     True
Ohio          False
Texas         False
Oregon        False
dtype: bool
California    False
Ohio           True
Texas          True
Oregon         True
dtype: bool


In [41]:
print(obj3 + obj4) #自动对齐计算

California        NaN
Ohio          70000.0
Oregon        32000.0
Texas         80000.0
Utah              NaN
dtype: float64


In [42]:
obj4.name = "population"
obj4.index.name = "state"
print(obj4)

state
California        NaN
Ohio          35000.0
Texas         40000.0
Oregon        16000.0
Name: population, dtype: float64


In [43]:
# DataFrame

In [45]:
data = {"state" : ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada"],
        "year" : [2000, 2001, 2002, 2001, 2002],
        "population" : [1.5, 1.7, 3.6, 2.4, 2.5]
       }
frame = DataFrame(data)
print(frame)

   population   state  year
0         1.5    Ohio  2000
1         1.7    Ohio  2001
2         3.6    Ohio  2002
3         2.4  Nevada  2001
4         2.5  Nevada  2002


In [46]:
DataFrame(data, columns=["year", "state", "population"]) # 手动指定列的顺序

year   state  population
0  2000    Ohio         1.5
1  2001    Ohio         1.7
2  2002    Ohio         3.6
3  2001  Nevada         2.4
4  2002  Nevada         2.5

In [49]:
frame2 = DataFrame(data, columns=["year", "state", "population", "debt"], 
                   index=["one", "two", "three", "four", "five"])
print(frame2)

       year   state  population debt
one    2000    Ohio         1.5  NaN
two    2001    Ohio         1.7  NaN
three  2002    Ohio         3.6  NaN
four   2001  Nevada         2.4  NaN
five   2002  Nevada         2.5  NaN


In [51]:
print(frame2.columns)
print(frame2["state"])

Index(['year', 'state', 'population', 'debt'], dtype='object')
one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object


In [68]:
print(frame2.ix[4])
print(frame2.loc[("one", "two"), :]) #获取行数据
print(frame2.iloc[1]) #获取行数据

year            2002
state         Nevada
population       2.5
debt             NaN
Name: five, dtype: object
     year state  population debt
one  2000  Ohio         1.5  NaN
two  2001  Ohio         1.7  NaN
year          2001
state         Ohio
population     1.7
debt           NaN
Name: two, dtype: object


In [74]:
frame2["debt"] = 16.5  #批量赋值
print(frame2)
frame2["debt"] = Series([-1.1, -1.1, 2.0], index=["one", "three", "four"]) # 单独赋值, 要索引对得上
print(frame2)

       year   state  population  debt
one    2000    Ohio         1.5  16.5
two    2001    Ohio         1.7  16.5
three  2002    Ohio         3.6  16.5
four   2001  Nevada         2.4  16.5
five   2002  Nevada         2.5  16.5
       year   state  population  debt
one    2000    Ohio         1.5  -1.1
two    2001    Ohio         1.7   NaN
three  2002    Ohio         3.6  -1.1
four   2001  Nevada         2.4   2.0
five   2002  Nevada         2.5   NaN


In [76]:
frame2["eastern"] = frame2.state == "Ohio" # 添加了一列
print(frame2)
del frame2["eastern"] # 删除一列
print(frame2)

       year   state  population  debt  eastern
one    2000    Ohio         1.5  -1.1     True
two    2001    Ohio         1.7   NaN     True
three  2002    Ohio         3.6  -1.1     True
four   2001  Nevada         2.4   2.0    False
five   2002  Nevada         2.5   NaN    False
       year   state  population  debt
one    2000    Ohio         1.5  -1.1
two    2001    Ohio         1.7   NaN
three  2002    Ohio         3.6  -1.1
four   2001  Nevada         2.4   2.0
five   2002  Nevada         2.5   NaN


In [78]:
# 嵌套字典创建DataFrame
# 外层键变成了列, 内层键变成了行标
pop = {
    "Nevada": {2001: 2.4, 2002: 2.9, },
    "Ohio": {2000: 1.5, 2001: 1.7, 2002: 2.5}
      }
frame3 = DataFrame(pop)
print(frame3)

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   2.5


In [80]:
print(frame3.T)  #转置

        2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   2.5


In [81]:
# 给定行列名
frame3.index.name = "year"
frame3.columns.name = "state"
print(frame3)

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   2.5


In [83]:
# 获取DataFrame的值
print(frame3.values)
print(frame2.values)

[[ nan  1.5]
 [ 2.4  1.7]
 [ 2.9  2.5]]
[[2000 'Ohio' 1.5 -1.1]
 [2001 'Ohio' 1.7 nan]
 [2002 'Ohio' 3.6 -1.1]
 [2001 'Nevada' 2.4 2.0]
 [2002 'Nevada' 2.5 nan]]


In [85]:
# 索引对象
obj = Series(range(3), index=["a", "b", "c"])
index = obj.index
print(index)
# index对象是不可变的
# index[1] = "d"
# print(index)

Index(['a', 'b', 'c'], dtype='object')


In [86]:
"""
    # 读写文本格式数据
"""

df = pd.read_csv("./data/week5/ex1.csv")
print(df)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo


In [88]:
pd.read_table("./data/week5/ex1.csv", sep=",")
# print(df)

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [89]:
pd.read_table("./data/week5/ex1.csv", sep=",", header=None)

0   1   2   3        4
0  a   b   c   d  message
1  1   2   3   4    hello
2  5   6   7   8    world
3  9  10  11  12      foo

In [91]:
names = ["a", "b", "c", "d", "message"]
df = pd.read_csv("./data/week5/ex2.csv", names=names)
print(df)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo


In [92]:
parsed = pd.read_csv("./data/week5/csv_mindex.csv", index_col=["key1", "key2"])
print(parsed)

           value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16


In [94]:
listed = open("./data/week5/ex3.txt").readlines()
# listed = list(open("./data/week5/ex3.txt"))
print(listed)

['            A         B         C\n', 'aaa -0.264438 -1.026059 -0.619500\n', 'bbb  0.927272  0.302904 -0.032399\n', 'ccc -0.264273 -0.386314 -0.217601\n', 'ddd -0.871858 -0.348382  1.100491\n']


In [96]:
result = pd.read_table("./data/week5/ex3.txt", sep="\s+")
print(result)

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491


In [98]:
# pd.read_csv("./data/week5/ex4.csv", skiprows=[0, 2, 3])
pd.read_csv("./data/week5/ex4.csv",)

# hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... NaN      NaN NaN      NaN
# who reads CSV files with computers                anyway? NaN NaN      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo

In [99]:
pd.read_csv("./data/week5/ex4.csv", skiprows=[0, 2, 3])


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [103]:
result = pd.read_csv("./data/week5/ex5.csv", na_values=["NULL", "world"])
print(result)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8     NaN
2     three  9  10  11.0  12     foo


In [102]:
pd.read_csv("./data/week5/ex5.csv")

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [104]:
sentinels = {'message': ["foo", "NA"], "something": ["two"]}
pd.read_csv("./data/week5/ex5.csv", na_values=sentinels) # 为每一列指定不同的缺失值

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [105]:
# 逐行读取文本文件
result = pd.read_csv("./data/week5/ex6.csv")
print(result)

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
5     1.817480  0.742273  0.419395 -2.251035   Q
6    -0.776764  0.935518 -0.332872 -1.875641   U
7    -0.913135  1.530624 -0.572657  0.477252   K
8     0.358480 -0.497572 -0.367016  0.507702   S
9    -1.740877 -1.160417 -1.637830  2.172201   G
10    0.240564 -0.328249  1.252155  1.072796   8
11    0.764018  1.165476 -0.639544  1.495258   R
12    0.571035 -0.310537  0.582437 -0.298765   1
13    2.317658  0.430710 -1.334216  0.199679   P
14    1.547771 -1.119753 -2.277634  0.329586   J
15   -1.310608  0.401719 -1.000987  1.156708   E
16   -0.088496  0.634712  0.153324  0.415335   B
17   -0.018663 -0.247487 -1.446522  0.750938   A
18   -0.070127 -1.579097  0.120892  0.671432   F
19   -0.194678 -0.49

In [108]:
pd.read_csv("./data/week5/ex6.csv", nrows=10)

one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q
5  1.817480  0.742273  0.419395 -2.251035   Q
6 -0.776764  0.935518 -0.332872 -1.875641   U
7 -0.913135  1.530624 -0.572657  0.477252   K
8  0.358480 -0.497572 -0.367016  0.507702   S
9 -1.740877 -1.160417 -1.637830  2.172201   G

In [129]:
# 分块读取
# chunk = pd.read_csv("./data/week5/ex6.csv", chunksize=1000)
chunk = pd.read_csv("./data/week5/ex6.csv")
# print(chunk.read())

In [138]:
chunk = pd.read_csv("./data/week5/ex6.csv", chunksize=1000)
tot = Series([])
for _ in chunk:
    tot = tot.add(_["key"].value_counts(), fill_value=0)
print(tot)

0    151.0
1    146.0
2    152.0
3    162.0
4    171.0
5    157.0
6    166.0
7    164.0
8    162.0
9    150.0
A    320.0
B    302.0
C    286.0
D    320.0
E    368.0
F    335.0
G    308.0
H    330.0
I    327.0
J    337.0
K    334.0
L    346.0
M    338.0
N    306.0
O    343.0
P    324.0
Q    340.0
R    318.0
S    308.0
T    304.0
U    326.0
V    328.0
W    305.0
X    364.0
Y    314.0
Z    288.0
dtype: float64


In [139]:
# 文件导出
tot.to_csv("./data/week5/tot.csv")

In [140]:
csv = Series.from_csv("./data/week5/tot.csv")
print(csv)

0    151.0
1    146.0
2    152.0
3    162.0
4    171.0
5    157.0
6    166.0
7    164.0
8    162.0
9    150.0
A    320.0
B    302.0
C    286.0
D    320.0
E    368.0
F    335.0
G    308.0
H    330.0
I    327.0
J    337.0
K    334.0
L    346.0
M    338.0
N    306.0
O    343.0
P    324.0
Q    340.0
R    318.0
S    308.0
T    304.0
U    326.0
V    328.0
W    305.0
X    364.0
Y    314.0
Z    288.0
dtype: float64


In [147]:
# 手工处理分隔符
import csv
f = open("./data/week5/ex7.csv")
# print(f.read())
reader = csv.reader(f)
print(reader.line_num)
for line in reader:
    print(line)

0
['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3', '4']


In [148]:
lines = list(csv.reader(open("./data/week5/ex7.csv")))
header, value = lines[0], lines[1:]
data_dict = {k:v for k, v in zip(header, value)}
print(data_dict)

{'a': ['1', '2', '3'], 'b': ['1', '2', '3', '4']}


In [152]:
class My_dialect(csv.Dialect):
    lineterminator = "\n"
    delimiter = ";"
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

with open("./data/week5/mydata.csv", "w") as f:
    writer = csv.writer(f, dialect=My_dialect)
    writer.writerow(("one", "two", "three"))
    writer.writerow((1, 2, 3)) 
    writer.writerow((4, 5, 6))
    writer.writerow((7, 8, 9)) 
pd.read_table("./data/week5/mydata.csv", sep=";")

one  two  three
0    1    2      3
1    4    5      6
2    7    8      9

In [160]:
# excel数据
# 生成xls工作薄
import xlrd
import xlwt

wb = xlwt.Workbook()

wb.add_sheet("first_sheet", cell_overwrite_ok=True)
wb.get_active_sheet()

ws_1 = wb.get_sheet(0)
print(ws_1)
ws_2 = wb.add_sheet("second_sheet")

data = np.arange(1, 65).reshape((8, 8))
print(data)
ws_1.write(0, 0, 100) # 写数据, 每次只能写一个格子

for c in range(data.shape[0]):
    for r in range(data.shape[1]):
        ws_1.write(c, r, int(data[c, r]))
        ws_2.write(c, r, int(data[r, c]))
wb.save("./data/week5/workbook.xls")

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [161]:
# 从工作薄里面读数据
book = xlrd.open_workbook("./data/week5/workbook.xls")
print(book, book.sheet_names())

<xlrd.book.Book object at 0x7f9506501198> ['first_sheet', 'second_sheet']


In [164]:
sheet_1 = book.sheet_by_name("first_sheet")
sheet_2 = book.sheet_by_index(1)
print(sheet_1.ncols, sheet_1.nrows)

8 8


In [171]:
for c in range(sheet_1.ncols):
    for r in range(sheet_1.nrows):
        print(sheet_1.cell(c, r).value, end="\t")
    print()

1.0	2.0	3.0	4.0	5.0	6.0	7.0	8.0	
9.0	10.0	11.0	12.0	13.0	14.0	15.0	16.0	
17.0	18.0	19.0	20.0	21.0	22.0	23.0	24.0	
25.0	26.0	27.0	28.0	29.0	30.0	31.0	32.0	
33.0	34.0	35.0	36.0	37.0	38.0	39.0	40.0	
41.0	42.0	43.0	44.0	45.0	46.0	47.0	48.0	
49.0	50.0	51.0	52.0	53.0	54.0	55.0	56.0	
57.0	58.0	59.0	60.0	61.0	62.0	63.0	64.0	


In [173]:
print(sheet_2.row(2), sheet_2.col_values(1))

[number:3.0, number:11.0, number:19.0, number:27.0, number:35.0, number:43.0, number:51.0, number:59.0] [9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0]


In [175]:
# 使用pandas读取xls
xls_file = pd.ExcelFile("./data/week5/workbook.xls")
table = xls_file.parse("first_sheet", header=None)
print(table)

    0   1   2   3   4   5   6   7
0   1   2   3   4   5   6   7   8
1   9  10  11  12  13  14  15  16
2  17  18  19  20  21  22  23  24
3  25  26  27  28  29  30  31  32
4  33  34  35  36  37  38  39  40
5  41  42  43  44  45  46  47  48
6  49  50  51  52  53  54  55  56
7  57  58  59  60  61  62  63  64


In [178]:
# 读取JSON
import json


obj = """
{
    "employees": [
        { "firstName":"Bill" , "lastName":"Gates" },
        { "firstName":"George" , "lastName":"Bush" },
        { "firstName":"Thomas" , "lastName":"Carter" }
        ]
}
"""
result = json.loads(obj)
print(result)

{'employees': [{'firstName': 'Bill', 'lastName': 'Gates'}, {'firstName': 'George', 'lastName': 'Bush'}, {'firstName': 'Thomas', 'lastName': 'Carter'}]}


In [183]:
asjson = json.dumps(result)
print(asjson)
print(type(asjson))

{"employees": [{"firstName": "Bill", "lastName": "Gates"}, {"firstName": "George", "lastName": "Bush"}, {"firstName": "Thomas", "lastName": "Carter"}]}
<class 'str'>


In [186]:
employees = DataFrame(result["employees"], columns=["firstName", "lastName"])
print(employees)

  firstName lastName
0      Bill    Gates
1    George     Bush
2    Thomas   Carter


In [188]:
# 持久化对象pickle
# import pickle

frame = pd.read_csv("./data/week5/ex1.csv")
print(frame)
frame.to_pickle("./data/week5/ex1.csv.pickle")

_ = pd.read_pickle("./data/week5/ex1.csv.pickle")
print(_)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo
   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo


In [189]:
# 使用HTML和 Web API
import requests
url = "https://api.github.com/repos/pydata/pandas/milestones/28/labels"
resp = requests.get(url)
print(resp)

<Response [200]>


In [190]:
data = json.loads(resp.text)
issue_labels = DataFrame(data)
print(issue_labels)

     color  default        id             name  \
0   e10c02    False     76811              Bug   
1   4E9A06    False     76812      Enhancement   
2   FCE94F    False    127681         Refactor   
3   75507B    False    129350            Build   
4   3465A4    False    134699             Docs   
5   AFEEEE    False    211840       Timeseries   
6   729FCF    False    233160          Groupby   
7   06909A    False   2301354          Data IO   
8   8AE234    False   2413328    Visualization   
9   0b02e1    False   2822098         Indexing   
10  d7e102    False   2822342     Missing-data   
11  a10c02    False   8935311      Performance   
12  02d7e1    False  13098779        Reshaping   
13  e102d8    False  31404521           Dtypes   
14  DDDDDD    False  32933285            Admin   
15  AD7FA8    False  35818298       API Design   
16  ffa0ff    False  42670965  Error Reporting   
17  006b75    False  47223669          Numeric   
18  5319e7    False  47229171           IO CSV   


In [191]:
# 使用数据库
