In [1]:
import numpy as np

In [2]:
"""通用函数"""
arr = np.arange(10)
print(arr)
print(np.sqrt(arr))
print(np.exp(arr)) # 求以e为底， arr为指数的函数值

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [3]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x, y)
print(np.maximum(x, y)) # 返回两个数组对应位置的最大值

[ 0.3847758   0.07076918 -1.14268194 -2.10482022 -1.28194997 -1.89612103
  0.27468064  0.51243487] [ 0.76580997 -0.25814649 -0.71210514  1.29709108 -0.09345348  0.18836199
 -0.08282441 -1.64772387]
[ 0.76580997  0.07076918 -0.71210514  1.29709108 -0.09345348  0.18836199
  0.27468064  0.51243487]


In [4]:
arr = np.random.randn(7) * 5
print(arr)
print(np.modf(arr)) # 返回两个数组， 分别是对应位置的整数部分和小数部分

[-1.82370718  1.91123071  9.07054421 -0.97992945 -3.28230507  0.14244786
 -3.37377396]
(array([-0.82370718,  0.91123071,  0.07054421, -0.97992945, -0.28230507,
        0.14244786, -0.37377396]), array([-1.,  1.,  9., -0., -3.,  0., -3.]))


In [5]:
"""利用数组进行数据处理"""
points = np.arange(-5, 5, 0.01) #一共一千个点
xs, ys = np.meshgrid(points, points)
print(xs)
print(ys)

import matplotlib.pyplot as plt

z = np.sqrt(xs ** 2 + ys ** 2)
print(z)
plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
plt.draw()
plt.show()

[[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 ...
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]]
[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]
[[7.07106781 7.06400028 7.05693985 ... 7.04988652 7.05693985 7.06400028]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 ...
 [7.04988652 7.04279774 7.03571603 ... 7.0286414  7.03571603 7.04279774]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]]


In [6]:
# 将条件逻辑转换为数组运算
xarr = np.arange(1.1, 1.6, 0.1)
yarr = np.arange(2.1, 2.6, 0.1)
print(xarr)
cond = np.array([True, False, True, True, False])

# python 写法
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print(result)

# numpy写法 where
result = np.where(cond, xarr, yarr)
print(result)

[1.1 1.2 1.3 1.4 1.5]
[1.1, 2.2, 1.3000000000000003, 1.4000000000000004, 2.5000000000000004]
[1.1 2.2 1.3 1.4 2.5]


In [7]:
# where表达式 
arr = np.random.randn(4, 4)
print(arr)
print(np.where(arr > 0, 2, -2))
print(np.where(arr > 0, 2, arr))

[[-1.05337448  0.41719208 -1.51380183  0.6050825 ]
 [ 1.33313007  0.32990652 -1.77127431  0.44064532]
 [ 0.44011626 -0.37145408  0.36456685 -1.08452093]
 [-0.38323164  0.13257195 -0.58722299 -0.03950233]]
[[-2  2 -2  2]
 [ 2  2 -2  2]
 [ 2 -2  2 -2]
 [-2  2 -2 -2]]
[[-1.05337448  2.         -1.51380183  2.        ]
 [ 2.          2.         -1.77127431  2.        ]
 [ 2.         -0.37145408  2.         -1.08452093]
 [-0.38323164  2.         -0.58722299 -0.03950233]]


In [8]:
"""数学与统计学方法"""
arr = np.random.randn(5, 4)
# =====================
print(arr.mean())
print(arr.sum())

print(np.mean(arr))
print(np.sum(arr))
# =====================
print(arr.mean(axis=1)) # 计算某个轴上的统计值
print(arr.sum(0))   # 还有var std min max  argmin, argmax(求最值的索引/下标) 可以选择是否计算某个轴

# ======================
# cumsum(某个方向上所有元素的累计和), cumprod（某个方向上所有元素的累计积） 必须指定轴向
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr.cumsum(0)) #每一列的累计和
print(arr.cumprod(1)) #每一行的累计积

-0.27001119300758
-5.400223860151599
-0.27001119300758
-5.400223860151599
[-0.54558478 -0.41710162  0.07646559 -0.22789215 -0.23594301]
[-2.66099161  2.31882032 -1.50639161 -3.55166097]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[  0   0   0]
 [  3  12  60]
 [  6  42 336]]


In [9]:
# 用于布尔型的数组方法
arr = np.random.randn(100)
print((arr > 0).sum()) #统计正值的数目

bools = np.array([True, False, True, False])
print(bools.any()) # 统计是否包含真值
print(bools.all()) # 统计是否所有值都是真

45
True
False


In [10]:
# 排序
arr = np.random.randn(10)
print(arr)
arr.sort()
print(arr)

arr = np.random.randn(5, 3)
new_arr = np.sort(arr, 0) # 不改变原来数组的值
print(new_arr) 
print("*" * 80)
print(arr)
arr.sort(0) # 按照第0个维度排序->改变原数组
print(arr)


[ 0.04745842  0.70807609  0.51773334 -0.33267134 -0.43443732  1.38010582
  0.31090516  1.4537815  -0.76301131  0.66742949]
[-0.76301131 -0.43443732 -0.33267134  0.04745842  0.31090516  0.51773334
  0.66742949  0.70807609  1.38010582  1.4537815 ]
[[-2.31191737 -0.86250436 -1.06962584]
 [-1.67373663 -0.47263687 -0.36166375]
 [-1.30467748 -0.17367126  0.19294313]
 [ 0.99030427 -0.16394096  0.56434785]
 [ 1.25919974  0.52567392  2.16772839]]
********************************************************************************
[[-2.31191737 -0.47263687 -1.06962584]
 [ 1.25919974 -0.16394096  2.16772839]
 [-1.30467748  0.52567392  0.56434785]
 [-1.67373663 -0.17367126 -0.36166375]
 [ 0.99030427 -0.86250436  0.19294313]]
[[-2.31191737 -0.86250436 -1.06962584]
 [-1.67373663 -0.47263687 -0.36166375]
 [-1.30467748 -0.17367126  0.19294313]
 [ 0.99030427 -0.16394096  0.56434785]
 [ 1.25919974  0.52567392  2.16772839]]


In [11]:
# 大数组排序
large_arr = np.random.randn(10000)
large_arr.sort()
print(large_arr[int(0.05 * len(large_arr))]) # 计算5%分位数

-1.6389635451096976


In [13]:
# 唯一化以及其他集合操作

names = np.array(["Bob", "Bob", "Alex", "Alex", "Shawn", "Bob"])
print(np.unique(names))
ints = np.array([1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
print(np.unique(ints))
print()

# 是否在数组中
print(np.in1d(ints, [1, 9, 4]))

['Alex' 'Bob' 'Shawn']
[1 2 3 4 5]

[ True  True  True  True False False False  True  True False]


In [14]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [18]:
print(x)
print(np.dot(x, np.ones(3)))
# print(x)

[[1 2 3]
 [4 5 6]]
[ 6. 15.]


In [21]:
np.random.seed(12345)
from numpy import linalg

X = np.random.randn(5, 5)
mat = X.T.dot(X)
print(X, mat)
print("*" * 20)
print(linalg.inv(mat))
print("=" * 20)
print(mat.dot(linalg.inv(mat)))

[[-0.20470766  0.47894334 -0.51943872 -0.5557303   1.96578057]
 [ 1.39340583  0.09290788  0.28174615  0.76902257  1.24643474]
 [ 1.00718936 -1.29622111  0.27499163  0.22891288  1.35291684]
 [ 0.88642934 -2.00163731 -0.37184254  1.66902531 -0.43856974]
 [-0.53974145  0.47698501  3.24894392 -1.02122752 -0.5770873 ]] [[ 4.07499325 -3.30588372 -1.30731336  3.44655322  2.61973938]
 [-3.30588372  6.15227438  1.71493621 -4.31933033 -0.09378269]
 [-1.30731336  1.71493621 11.11872134 -3.37023945 -2.00972893]
 [ 3.44655322 -4.31933033 -3.37023945  4.78118413  0.03314614]
 [ 2.61973938 -0.09378269 -2.00972893  0.03314614  7.77364994]]
********************
[[ 3.03609983 -0.1808297  -0.68779105 -2.82852163 -1.19110946]
 [-0.1808297   0.50346566  0.12149398  0.6701624   0.0955664 ]
 [-0.68779105  0.12149398  0.29039878  0.80814474  0.30488423]
 [-2.82852163  0.6701624   0.80814474  3.4151871   1.15567215]
 [-1.19110946  0.0955664   0.30488423  1.15567215  0.60509381]]
[[ 1.00000000e+00 -1.17862974e-

In [22]:
q, r = linalg.qr(mat)
print(q)
print(r)

[[-0.58826489 -0.26193758 -0.20133733 -0.32332868 -0.66351712]
 [ 0.47723645 -0.66087638  0.17336075 -0.55009068  0.05323603]
 [ 0.18872339 -0.08064978 -0.96349735 -0.02658815  0.16983822]
 [-0.49754346  0.16181903  0.01788116 -0.55811936  0.64377648]
 [-0.37818485 -0.67966266  0.02761245  0.5297685   0.33707238]]
[[ -6.92714002   7.38899524   6.12272905  -7.11625341  -4.92150833]
 [  0.          -3.97347612  -0.86707993   2.97472904  -5.74024113]
 [  0.           0.         -10.26810228   1.89090298   1.60790112]
 [  0.           0.           0.          -1.29964934   3.35772244]
 [  0.           0.           0.           0.           0.55705805]]


In [50]:
# ============== 模拟随机漫步 =================
NUMS = 1000
import time
import random

start = time.time()

res = 0
pos = []

for x in range(1000):
    step = random.choice([-1, 1])
    res += step
    pos.append(res)
print(max(pos), min(pos))
print(res)
print((time.time() - start)*1000)


8 -43
-40
4.474878311157227


In [51]:
start = time.time()
steps = np.random.choice([-1, 1], size=1000)
positions = steps.cumsum()
print(steps.sum(), positions.max(), positions.min())
print((time.time()-start)*1000)

-10 17 -19
0.9262561798095703


In [74]:
# 一次模拟五千个随机漫步
walks = np.random.choice([-1, 1], size=(5000, 1000))
res = walks.cumsum(0)
print(res)
print(res.max(), res.min())
print("=" * 50)
# 随机漫步走到30的情况
hits = (np.abs(res) >= 30).any(1)
print(hits.sum())

[[   1   -1   -1 ...   -1   -1   -1]
 [   2    0   -2 ...   -2    0    0]
 [   1   -1   -3 ...   -3   -1    1]
 ...
 [  -4   -2 -158 ... -216   26  -94]
 [  -5   -1 -159 ... -217   25  -95]
 [  -6   -2 -158 ... -216   24  -96]]
240 -316
4926


In [71]:
# 正态分布随机漫步

steps = np.random.normal

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa